# Generated by Django 5.2.4 on 2025-07-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="approved_limit",
            field=models.IntegerField(default=0),
        ),
    ]
